version: '3.8'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db    
    restart: always
    tty: true
    volumes:      
      - ./sql:/docker-entrypoint-initdb.d      
    environment:
      - MYSQL_DATABASE=$DATABASE_NAME
      - MYSQL_ROOT_PASSWORD=$DATABASE_PASSWORD
    ports:
      - "3306:3306"
    networks:
      - challenge-network  
  app:
    build:
      context: app
    container_name: app    
    networks:
      - challenge-network
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - ".env"
    tty: true
    depends_on:
      - web
      - db
  web:
    container_name: web       
    restart: always
    build:
      context: ./nginx
    ports:
      - "8080:80"
    networks:
      - challenge-network
    depends_on:
      - db
  
networks:
  challenge-network:
    driver: bridge
